// <auto-generated />
namespace IdentitySample.Migration.ScoreSystem
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddImageField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddImageField));
        
        string IMigrationMetadata.Id
        {
            get { return "201501211612498_AddImageField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
